'use client'

import Head from 'next/head'
import RandomFox from './components/RandomFox';
import { MouseEventHandler, useState } from 'react';

type ImageItems = {
  id: string,
  url: string,
}

export default function Home() {
  const random = () => Math.floor(Math.random() * 123) + 1;
  const generateId = () => Math.random().toString(36).substr(2, 9);
  const [images, setImages] = useState<Array<ImageItems>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    const newImageItem: ImageItems = {
      id: generateId(),
      url: `https://randomfox.ca/images/${random()}.jpg`
    }
    setImages([...images,newImageItem]);
  }

  return (
    <div>
      <Head>
        <title>Platzi </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='w-10/12 mx-auto my-5'>
        <h1 className='text-4xl'>Generador de imágenes de zorritos</h1>
        <div className='flex gap-5 flex-wrap'>
          {images &&
            images.map(({ id, url }) => (
              <div key={id}>
                <RandomFox
                  image={url}
                  alt={'Imagen'}
                />
              </div>
            ))
          }
        </div>
        <button className="bg-blue-500 p-3 rounded-lg my-5 text-white" onClick={(event) => addNewFox(event)}>Añadir zorrito</button>
      </main>
    </div>
  );
}