'use client'

import Head from 'next/head'
import { MouseEventHandler, useState } from 'react';
import LazyImage from './components/RandomFox';
import { random } from "lodash";

export default function Home() {
  const myRandom = () => random(1, 123);
  const generateId = () => Math.random().toString(36).substr(2, 9);
  const [images, setImages] = useState<Array<IFoxImageItem>>([]);

  const addNewFox: MouseEventHandler<HTMLButtonElement> = (event) => {
    const newImageItem: IFoxImageItem = {
      id: generateId(),
      url: `https://randomfox.ca/images/${myRandom()}.jpg`
    }
    setImages([...images, newImageItem]);
    window.plausible("Add_fox");
  }

  return (
    <div>
      <Head>
        <title>Platzi </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script defer data-domain="yourdomain.com" src="https://plausible.io/js/script.js"></script>
      </Head>
      <main className='w-10/12 mx-auto my-5'>
        <h1 className='text-4xl'>Generador de imágenes de zorritos</h1>
        <div className='flex gap-5 flex-wrap'>
          {images &&
            images.map(({ id, url }) => (
              <div key={id} className="p-4">
                <LazyImage
                  image={url}
                  className="rounded-lg shadow-xl bg-gray-300"
                  width={320}
                  title="Random fox"
                  height="auto"
                  onClick={() => console.log("Hey")}
                  alt={"Imagen zorrito"}
                />
              </div>
            ))}
        </div>
        <button className="bg-blue-500 p-3 rounded-lg my-5 text-white" onClick={(event) => addNewFox(event)}>Añadir zorrito</button>
      </main>
    </div>
  );
}